import subprocess, os

issue = os.environ.get("ISSUE_NUMBER", "unknown")

subprocess.run([
    "gh", "pr", "create",
    "--title", f"Agent fix for issue #{issue}",
    "--body", "Automatically generated by LLM agent",
    "--base", "main",
    "--head", f"agent-fix-{issue}"
], check=True)

subprocess.run([
    "gh", "pr", "merge",
    "--auto",
    "--squash"
], check=True)
